### ISSUE TITLE
已安装lxml，还是提示未安装无法使用。

### ISSUE THREAD

**Issue by Tamamoimoto** [Nana-Miko/GengSearch#2]
系统为armbian(Linux onecloud 5.18.0-rc3-meson #trunk SMP Thu Jun 30 13:19:36 UTC 2022 armv7l GNU/Linux
)
已安装:lxml-4.9.1
mirai无报错

root@onecloud:/mnt/disk01/pybot# python3 GengSearch.py
/mnt/disk01/pybot/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.10) or chardet (5.0.0)/charset_normalizer (2.1.0) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
Version 1.3.2
running from Linux

*中间配置信息已删除*

data Get Success
Listening……
Get mission
Searchid: <!doctype html>
<html data-n-head-ssr>
  <head >
    <title>退出登录...</title><meta data-n-head=
infoUrl: https://jikipedia.com/definition/<!doctype html>
<html data-n-head-ssr>
  <head >
    <title>退出登录...</title><meta data-n-head=
Error
错误详情:
Traceback (most recent call last):
  File "/mnt/disk01/pybot/GengSearch.py", line 173, in Search
    soup = BeautifulSoup(infolist, "lxml")
  File "/mnt/disk01/pybot/bs4/__init__.py", line 245, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

save log
save log

Listening……

**Comment by JHue58** [comment]
小鸡词典的网页更新了，之前的爬虫代码用不了了)悲

**Comment by Tamamoimoto** [comment]
> 小鸡词典的网页更新了，之前的爬虫代码用不了了)悲

好的_(:з」∠)_
